language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="55c28b67-172b-4128-8fcb-64391f234c14"
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - vasiliy.krasov@gmail.com
    on_success: never # default: change
    on_failure: always # default: always